version: 2

build:
  image: latest
  tools:
    python: "3.9"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt

    - method: pip

    path: .
